language: php

dist: trusty

php:
  - 5.6
  - 7
  - 7.1
  - hhvm
  # looks like hhvm has a bug somewhere...

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
